apiVersion: v1
kind: Service
metadata:
 name: webapp-application-service
spec:
 ports:
 - name: http
   protocol: TCP
   port: 80
   targetPort: 8080
 externalIPs:
 - 18.118.14.194
 selector:
   app: my-app
 type: LoadBalancer
