apiVersion: v1
kind: Service
metadata:
 name: webapp-application-service
spec:
 ports:
 - name: http
   protocol: TCP
   port: 80
   targetPort: 8080
 externalIPs:
 - 3.20.203.76
 selector:
   app: my-app
 type: LoadBalancer
